Repository netguru-code-college/vol3-violet, pull requests merged in 2018-08, with the labels that each got.

#3 Add bootstrap gem
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.scss
Labels: Ready for review

#4 [WIP] User authentication
  Gemfile
  Gemfile.lock
  app/assets/javascripts/home.coffee
  app/assets/stylesheets/home.scss
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/helpers/home_helper.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20180823143414_devise_create_users.rb
  db/schema.rb
  spec/controllers/home_controller_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: Work in progress

#25 Creating ban service
  app/controllers/users_controller.rb
  app/models/ability.rb
  app/services/ban_user.rb
  app/views/users/_users_listing.html.erb
Labels: Ready for review

#27 Fix associations
  app/models/bill.rb
  app/models/debt.rb
  app/models/user.rb
  db/migrate/20180828071850_rename_user_id_column_in_bills_to_payer_id.rb
  db/migrate/20180828072554_rename_user_id_column_in_debts_to_borrower_id.rb
  db/schema.rb
Labels: Review done

#28 Add service objects to create bills and corresponding debts (splitted…
  app/controllers/bills_controller.rb
  app/models/bill.rb
  app/models/group.rb
  app/services/bills/create_debts_service.rb
  app/services/bills/create_service.rb
Labels: Ready for review

#45 Allow miltiple emails
  app/controllers/groups_controller.rb
  app/views/groups/_form.html.erb
  config/environments/development.rb
  config/initializers/carrierwave.rb
Labels: Review done

#46 Fix bug where extra empty debt was created when creating bill
  app/controllers/bills_controller.rb
  app/services/bills/create_service.rb
  app/views/users/_debt_details.html.erb
Labels: Ready for review

#44 QA miko
  app/assets/stylesheets/application.scss
  app/views/groups/_bills_details.html.erb
  app/views/groups/bills.js.erb
  app/views/groups/index.html.erb
  app/views/groups/show.html.erb
  app/views/users/_group_details.html.erb
Labels: Review done
